In [13]:
pwd

'/Users/lubina.zaidi/Documents/Claims audit and fraud detection'

In [1]:
import pandas as pd
import numpy as np

In [2]:
# =====================================================
# LOAD FILES
# =====================================================

manual = pd.read_excel("KM_US_Mannual_Pass.xlsx")
ledger = pd.read_excel("KM_PROMOTION_PAYOUT_QUERY_RESULTS.xlsx")
claims = pd.read_excel("claim_payout_qury_result.xlsx")

In [3]:
manual.head(2)

,FulfillmentDate,ParticipantName,PromotionName,PromoDisplayName,PointsPaid,EntityName,EntityID,CurrentTitle,Participant Title On Paid Date,ContactStatus,Hierarchy,PromotionID,PSPS
0,2025-12-18 06:02:00,Leigh Anne Romaine,FY25 Q2 KMRY Claims Adjustment Blue Technologi...,FY25 Q2 KMRY Claims Adjustment,615,"BLUE TECHNOLOGIES, INC.",26102,Sales/Marketing Representative,Sales/Marketing Representative,Active,Corporate>>Dealers US>>Dealers CE>>Dealers CE ...,2048191,550319001104
1,2024-06-26 05:02:00,Aaron Fitzwater,Healthcare Sales Certification Points (EAST 6-...,Healthcare Sales Certification Points (EAST 6-...,300,"EDWARDS BUSINESS MACHINES, INC.",406779,Sales/Marketing Representative,Sales/Marketing Representative,Active,Corporate>>Dealers US>>Dealers EA>>Dealers EA ...,1308823,550319001106

In [5]:
manual.columns

Index(['FulfillmentDate', 'ParticipantName', 'PromotionName',
       'PromoDisplayName', 'PointsPaid', 'EntityName', 'EntityID',
       'CurrentTitle', 'Participant Title On Paid Date', 'ContactStatus',
       'Hierarchy', 'PromotionID', 'PSPS'],
      dtype='str')

In [6]:
ledger.head(2)

,LedgerId,DataKeyType,Fulfillmentdate,FirstName,LastName,FullName,UserName,ClientParticipantId,EntityName,ClientEntityId,...,DollarsEarned,PromotionType,Comments,PersonEID,ProgramEID,DataSource,GameName,GamePlaysEarned,PSPS,PromoSalesType
0,126520,LDGR,2026-09-25 07:13:00,Floyd,Hood,Floyd Hood,floyd_hood,floyd_hood,"PACIFIC OFFICE AUTOMATION, INC.",26429,...,NaN,Do and Get,NaN,111998,103930,Claims,NaN,NaN,550319001103,SWR
1,126521,LDGR,2026-09-25 07:13:00,Ryan,Stuempfig,Ryan Stuempfig,ryan_stuempfig,ryan_stuempfig,"PACIFIC OFFICE AUTOMATION, INC.",26429,...,NaN,Do and Get,NaN,454376,103930,Claims,NaN,NaN,550319001103,SWR

In [7]:
ledger.columns

Index(['LedgerId', 'DataKeyType', 'Fulfillmentdate', 'FirstName', 'LastName',
       'FullName', 'UserName', 'ClientParticipantId', 'EntityName',
       'ClientEntityId', 'Title', 'Hierarchy', 'ProgramName', 'PromotionId',
       'PromotionName', 'PromotionDisplayName', 'AwardType', 'PointsEarned',
       'DollarsEarned', 'PromotionType', 'Comments', 'PersonEID', 'ProgramEID',
       'DataSource', 'GameName', 'GamePlaysEarned', 'PSPS', 'PromoSalesType'],
      dtype='str')

In [8]:
claims.head(2)

,InvoiceNumber,ClaimEId,EntityClaimItemEID,ClaimFormName,ClaimSubmittedDate,ClaimItemStatus,ClaimStatusReason,AwardDate,AwardAmount,PromotionName,...,LIIndustryId,CompetitorKnockOut,EntityName,EntityId,PSPS,PromoSalesType,MasterDealerID,MasterDealerName,DealerSoldToID,DealerSoldToName
0,JennyKarcher9282023106AM,1027522,1027523,Dealer Claim Form,09/28/2023,Processed,Completed,NaN,NaN,NaN,...,Healthcare,NaN,"PERRY PRO TECH, INC.",407294,NaN,NaN,NaN,NaN,NaN,NaN
1,JennyKarcher9282023106AM,1027522,1027524,Dealer Claim Form,09/28/2023,Processed,Completed,NaN,NaN,NaN,...,Healthcare,NaN,"PERRY PRO TECH, INC.",407294,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
claims.columns

Index(['InvoiceNumber', 'ClaimEId', 'EntityClaimItemEID', 'ClaimFormName',
       'ClaimSubmittedDate', 'ClaimItemStatus', 'ClaimStatusReason',
       'AwardDate', 'AwardAmount', 'PromotionName', 'ParticipantId',
       'ParticipantName', 'ParticipantTitle', 'ParticipantEmailAddress',
       'ProductName', 'ProductId', 'ProductSerialNumber', 'Quantity',
       'SaleDate', 'CommentText', 'InternalComment', 'LIIndustryId',
       'CompetitorKnockOut', 'EntityName', 'EntityId', 'PSPS',
       'PromoSalesType', 'MasterDealerID', 'MasterDealerName',
       'DealerSoldToID', 'DealerSoldToName'],
      dtype='str')

In [4]:
# =====================================================
# STANDARDIZE COLUMN NAMES
# =====================================================

manual.columns = manual.columns.str.strip()
ledger.columns = ledger.columns.str.strip()
claims.columns = claims.columns.str.strip()

In [5]:
# =====================================================
# HELPER FUNCTIONS
# =====================================================

def clean_text(series):
    return (
        series.astype(str)
        .str.strip()
        .str.upper()
        .str.replace(r"\s+", " ", regex=True)
    )

def clean_id(series):
    return (
        series.astype(str)
        .str.strip()
        .str.replace(".0", "", regex=False)
    )

In [6]:
# =====================================================
# CLEAN MANUAL PASS FILE
# =====================================================

manual["ParticipantName_clean"] = clean_text(manual["ParticipantName"])
manual["PromotionName_clean"] = clean_text(manual["PromotionName"])

manual["PromotionID_clean"] = clean_id(manual["PromotionID"])
manual["EntityID_clean"] = clean_id(manual["EntityID"])
manual["PSPS_clean"] = clean_text(manual["PSPS"])

manual["PointsPaid"] = pd.to_numeric(
    manual["PointsPaid"],
    errors="coerce"
)

manual["FulfillmentDate"] = pd.to_datetime(
    manual["FulfillmentDate"],
    errors="coerce"
)

In [7]:
manual.head(1)

,FulfillmentDate,ParticipantName,PromotionName,PromoDisplayName,PointsPaid,EntityName,EntityID,CurrentTitle,Participant Title On Paid Date,ContactStatus,Hierarchy,PromotionID,PSPS,ParticipantName_clean,PromotionName_clean,PromotionID_clean,EntityID_clean,PSPS_clean
0,2025-12-18 06:02:00,Leigh Anne Romaine,FY25 Q2 KMRY Claims Adjustment Blue Technologi...,FY25 Q2 KMRY Claims Adjustment,615,"BLUE TECHNOLOGIES, INC.",26102,Sales/Marketing Representative,Sales/Marketing Representative,Active,Corporate>>Dealers US>>Dealers CE>>Dealers CE ...,2048191,550319001104,LEIGH ANNE ROMAINE,FY25 Q2 KMRY CLAIMS ADJUSTMENT BLUE TECHNOLOGI...,2048191,26102,550319001104

In [8]:
manual.columns

Index(['FulfillmentDate', 'ParticipantName', 'PromotionName',
       'PromoDisplayName', 'PointsPaid', 'EntityName', 'EntityID',
       'CurrentTitle', 'Participant Title On Paid Date', 'ContactStatus',
       'Hierarchy', 'PromotionID', 'PSPS', 'ParticipantName_clean',
       'PromotionName_clean', 'PromotionID_clean', 'EntityID_clean',
       'PSPS_clean'],
      dtype='str')

In [9]:
manual_analysis = manual.groupby(['EntityID','ParticipantName','PromotionName','EntityName','ContactStatus'])["PointsPaid"] \
      .agg(["count","sum"]).reset_index().sort_values(by="sum", ascending=False)    

manual_analysis

,EntityID,ParticipantName,PromotionName,EntityName,ContactStatus,count,sum
2110,26422,Tim Hicks,FY23 Q3 Application Specialist Override Points...,"LOFFLER BUSINESS SYSTEMS, LLC",Active,2,44000
3924,406821,Danny Wayne,FY25 Q4 All Copy Claims Adjustment (D. Wayne),"ALL COPY PRODUCTS, LLC",Active,1,42128
294,105249,Robbie Vaughn,FY23 Q1 Production Print Overrides - Central (...,DBA PROSOURCE,Active,1,37000
2056,26359,Dennis Allison,FY26 Q1 KMRY Points Adjustment (Systel),"SYSTEL BUSINESS EQUIPMENT CO., INC.",Active,1,34810
2050,26359,Dennis Allison,FY23 Q3 KMRY Points - Systel (Dennis Allison),"SYSTEL BUSINESS EQUIPMENT CO., INC.",Active,1,34370
...,...,...,...,...,...,...,...
442,1119010,Adam Guyer,Atlantic Manager Overrides (FY24 September 2024),DBA ATLANTIC TOMORROWS OFFICE,Inactive,1,2
1282,252850,Emma Spurlock,Chill and Thrill Claims Adjustment Novatech Au...,DBA NOVATECH-MEMPHIS,Active,1,2
4385,406821,Travis Haas,All Copy Manager Overrides (FY24 January)\t,"ALL COPY PRODUCTS, LLC",Active,1,2
4435,406821,Tyler Cunha,Healthcare Sales Certification Points (WEST 12...,"ALL COPY PRODUCTS, LLC",Inactive,1,1
1170,1740938,Justin Moody,FY26 Q2 KMRY Claims Adjustment XBS Digital (J ...,DBA XBS DIGITAL,Active,1,1

In [10]:
manual_analysis["count"].value_counts()

count
1    4804
2     256
3      16
4       1
Name: count, dtype: int64

In [11]:
manual_analysis[manual_analysis["count"] >=2].sort_values(by="count", ascending=False)

,EntityID,ParticipantName,PromotionName,EntityName,ContactStatus,count,sum
2435,26429,Eric Bird,FY26 KM Rewards You Claim Adjustment POA (E Bi...,"PACIFIC OFFICE AUTOMATION, INC.",Active,4,1000
64,100240582,John Spriggs,Happy Holidays!,"UBEO WEST, LLC",Inactive,3,300
4838,604,Kurt Louys,FY23 Q3 HP Incentive - 02.2024,Heartland Sls,Active,3,1950
5065,Field - BUS,Jon Brumbelow,2025 Ride To End ALZ DBM/RDM Contest Winners (...,Field Employees - BUS,Active,3,564
1229,252850,Brad Benton,Novatech - Manager Overrides (FY25 Q2),DBA NOVATECH-MEMPHIS,Active,3,681
...,...,...,...,...,...,...,...
1528,25895,Anthony Elliott,FY24 Q1 Claims - Corrected Title (Clines-Elliott),"CLINE'S BUSINESS EQUIPMENT, INC.",Active,2,970
183,100248448,Shawn Moran,UBEO KMRY Program - Manager Override Points FY...,DBA UBEO EAST,Active,2,914
170,100248448,Mike Davis,Dealer UBEO East FY24 Q1 KMRY Program Point Ad...,DBA UBEO EAST,Active,2,890
197,100248448,William Thacker,UBEO KMRY Program - Manager Override Points (F...,DBA UBEO EAST,Active,2,878
67,100240582,Sam Barber,UBEO KMRY Program - Manager Override Points FY...,"UBEO WEST, LLC",Active,2,4

In [12]:
manual_analysis[manual_analysis["count"] >=3].sort_values(by="sum", ascending=False)

,EntityID,ParticipantName,PromotionName,EntityName,ContactStatus,count,sum
4835,602,Rich Fredenburgh,FY23 Q3 HP Incentive - 02.2024,Mid-Atlantic Sls,Active,3,15600
63,100240582,Jeff Patterson,UBEO West FY24 Q1 KMRY Program Missing Points,"UBEO WEST, LLC",Active,3,2019
4838,604,Kurt Louys,FY23 Q3 HP Incentive - 02.2024,Heartland Sls,Active,3,1950
5067,Field - BUS,Jon Brumbelow,Ride To End ALZ Sales Contest Winner 11-18-2024,Field Employees - BUS,Active,3,1500
4840,606,Ben Cervantez Ramos,FY23 Q3 HP Incentive - 02.2024,West Sls,Active,3,1500
1230,252850,Brad Benton,Novatech KMRY Manager Overrides (FY25 Q4),DBA NOVATECH-MEMPHIS,Active,3,1212
1228,252850,Brad Benton,Novatech KMRY Manager Overrides (FY25 Q3),DBA NOVATECH-MEMPHIS,Active,3,1062
4833,601,James Hodgdon,FY23 Q3 HP Incentive - 02.2024,Northeast Sls,Active,3,1050
2435,26429,Eric Bird,FY26 KM Rewards You Claim Adjustment POA (E Bi...,"PACIFIC OFFICE AUTOMATION, INC.",Active,4,1000
2958,31054,Charles Curtis,FY23 Q4 Healthcare Sales Certification Points ...,DBA FLEXTG - HQ,Active,3,900
1231,252850,Brad Benton,Novatech KMRY Manager Overrides (FY26 Q1)\t,DBA NOVATECH-MEMPHIS,Active,3,837
5066,Field - BUS,Jon Brumbelow,ALZ Go The Extra Mile Contest Winners,Field Employees - BUS,Active,3,750
1229,252850,Brad Benton,Novatech - Manager Overrides (FY25 Q2),DBA NOVATECH-MEMPHIS,Active,3,681
1423,252850,Tekoa Hawkins,Application Specialist KMRY Points FY25 Januar...,DBA NOVATECH-MEMPHIS,Active,3,630
5065,Field - BUS,Jon Brumbelow,2025 Ride To End ALZ DBM/RDM Contest Winners (...,Field Employees - BUS,Active,3,564
5050,Field - BUS,Brian Warbis,FY23 Q3 HP Incentive - 02.2024,Field Employees - BUS,Active,3,525
64,100240582,John Spriggs,Happy Holidays!,"UBEO WEST, LLC",Inactive,3,300

In [13]:
manual_analysis.PromotionName.value_counts()

PromotionName
FY22 Q4 Public Sector Sales Certification Points        108
KMRY Points for 017 Product ID'S                         88
Happy Holidays!                                          77
POA Loyalty Pays / Extra KMAP Claim Payout               63
POA KMAP Claims (February/March 2023)                    62
                                                       ...
FY24 KMRY - Missing Points (Campione-Visual Edge)         1
Edwards FY 22 1H VP Sales Overrides                       1
FY24 Q4 KMRY Missing Points - CPI 3-28-2025               1
FY24 Q3 KMRY Point Adjustment Fishers S Scotton           1
FY26 Q2 KMRY Claims Adjustment XBS Digital (J Moody)      1
Name: count, Length: 1237, dtype: int64

In [14]:
# =====================================================
# CLEAN PAYOUT LEDGER
# =====================================================

ledger["FullName_clean"] = clean_text(ledger["FullName"])
ledger["PromotionName_clean"] = clean_text(ledger["PromotionName"])

ledger["PromotionId_clean"] = clean_id(ledger["PromotionId"])
ledger["ClientEntityId_clean"] = clean_id(ledger["ClientEntityId"])
ledger["ClientParticipantId_clean"] = clean_id(
    ledger["ClientParticipantId"]
)

ledger["PSPS_clean"] = clean_text(ledger["PSPS"])

ledger["PointsEarned"] = pd.to_numeric(
    ledger["PointsEarned"],
    errors="coerce"
)

ledger["FulfillmentDate"] = pd.to_datetime(
    ledger["Fulfillmentdate"],
    errors="coerce"
)

In [15]:
# =====================================================
# CLEAN CLAIMS
# =====================================================

claims["ParticipantName_clean"] = clean_text(
    claims["ParticipantName"]
)

claims["PromotionName_clean"] = clean_text(
    claims["PromotionName"]
)

claims["ParticipantId_clean"] = clean_id(
    claims["ParticipantId"]
)

claims["EntityId_clean"] = clean_id(
    claims["EntityId"]
)

claims["PSPS_clean"] = clean_text(
    claims["PSPS"]
)

claims["AwardAmount"] = pd.to_numeric(
    claims["AwardAmount"],
    errors="coerce"
)

claims["ClaimSubmittedDate"] = pd.to_datetime(
    claims["ClaimSubmittedDate"],
    errors="coerce"
)

In [16]:
len(claims)

159816

In [17]:
len(ledger)

37478

In [18]:
# =====================================================
# 1. CLAIMS -> LEDGER MATCH
# =====================================================

claims_ledger = claims.merge(
    ledger,
    left_on=[
        "ParticipantId_clean",
        "EntityId_clean",
        "PSPS_clean",
        "PromotionName_clean"
    ],
    right_on=[
        "ClientParticipantId_clean",
        "ClientEntityId_clean",
        "PSPS_clean",
        "PromotionName_clean"
    ],
    how="left",
    indicator=True,
    suffixes=("_claim", "_ledger")
)

claims_ledger["AmountMatch"] = (claims_ledger["AwardAmount"] == claims_ledger["PointsEarned"])

In [19]:
claims_ledger

,InvoiceNumber,ClaimEId,EntityClaimItemEID,ClaimFormName,ClaimSubmittedDate,ClaimItemStatus,ClaimStatusReason,AwardDate,AwardAmount,PromotionName_claim,...,GamePlaysEarned,PSPS_ledger,PromoSalesType_ledger,FullName_clean,PromotionId_clean,ClientEntityId_clean,ClientParticipantId_clean,FulfillmentDate,_merge,AmountMatch
0,JennyKarcher9282023106AM,1027522,1027523,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
1,JennyKarcher9282023106AM,1027522,1027524,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
2,JennyKarcher9282023106AM,1027522,1027525,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
3,JennyKarcher9282023106AM,1027522,1027526,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
4,JennyKarcher9282023112AM,1027528,1027527,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159811,NiklasVonderhaar061120241100am,1297735,1297753,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
159812,NiklasVonderhaar061120241100am,1297735,1297755,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
159813,NiklasVonderhaar061120241100am,1297735,1297760,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
159814,NiklasVonderhaar061120241100am,1297735,1297769,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False
159815,NiklasVonderhaar061120241100am,1297735,1297775,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False

In [20]:
claims_ledger["PromotionMatch"] = (
    claims_ledger["PromotionName_claim"]
    .str.upper().str.strip()
    ==
    claims_ledger["PromotionName_ledger"]
    .str.upper().str.strip()
)

claims_ledger["AmountMatch"] = (
    claims_ledger["AwardAmount"]
    ==
    claims_ledger["PointsEarned"]
)

In [21]:
claims_ledger

,InvoiceNumber,ClaimEId,EntityClaimItemEID,ClaimFormName,ClaimSubmittedDate,ClaimItemStatus,ClaimStatusReason,AwardDate,AwardAmount,PromotionName_claim,...,PSPS_ledger,PromoSalesType_ledger,FullName_clean,PromotionId_clean,ClientEntityId_clean,ClientParticipantId_clean,FulfillmentDate,_merge,AmountMatch,PromotionMatch
0,JennyKarcher9282023106AM,1027522,1027523,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
1,JennyKarcher9282023106AM,1027522,1027524,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
2,JennyKarcher9282023106AM,1027522,1027525,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
3,JennyKarcher9282023106AM,1027522,1027526,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
4,JennyKarcher9282023112AM,1027528,1027527,Dealer Claim Form,2023-09-28,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159811,NiklasVonderhaar061120241100am,1297735,1297753,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
159812,NiklasVonderhaar061120241100am,1297735,1297755,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
159813,NiklasVonderhaar061120241100am,1297735,1297760,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
159814,NiklasVonderhaar061120241100am,1297735,1297769,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False
159815,NiklasVonderhaar061120241100am,1297735,1297775,Dealer Claim Form,2024-06-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,left_only,False,False

In [22]:
claims_ledger['AmountMatch'].value_counts()

AmountMatch
False    159816
Name: count, dtype: int64

In [23]:
claims_ledger['PromotionMatch'].value_counts()

PromotionMatch
False    159816
Name: count, dtype: int64

In [24]:
# =====================================================
# 2. MANUAL PASS -> LEDGER MATCH
# =====================================================

manual_ledger = manual.merge(
    ledger,
    left_on=[
        "PromotionID_clean",
        "EntityID_clean",
        "PSPS_clean",
        "ParticipantName_clean"
    ],
    right_on=[
        "PromotionId_clean",
        "ClientEntityId_clean",
        "PSPS_clean",
        "FullName_clean"
    ],
    how="left",
    indicator=True,
    suffixes=("_manual", "_ledger")
)

manual_ledger["AmountMatch"] = (
    manual_ledger["PointsPaid"]
    ==
    manual_ledger["PointsEarned"]
)

In [25]:
manual_ledger.head(2)

,FulfillmentDate_manual,ParticipantName,PromotionName_manual,PromoDisplayName,PointsPaid,EntityName_manual,EntityID,CurrentTitle,Participant Title On Paid Date,ContactStatus,...,PSPS_ledger,PromoSalesType,FullName_clean,PromotionName_clean_ledger,PromotionId_clean,ClientEntityId_clean,ClientParticipantId_clean,FulfillmentDate_ledger,_merge,AmountMatch
0,2025-12-18 06:02:00,Leigh Anne Romaine,FY25 Q2 KMRY Claims Adjustment Blue Technologi...,FY25 Q2 KMRY Claims Adjustment,615,"BLUE TECHNOLOGIES, INC.",26102,Sales/Marketing Representative,Sales/Marketing Representative,Active,...,5.503190e+11,NaN,LEIGH ANNE ROMAINE,FY25 Q2 KMRY CLAIMS ADJUSTMENT BLUE TECHNOLOGI...,2048191,26102,leighanne_romaine,2025-12-18 06:02:00,both,True
1,2024-06-26 05:02:00,Aaron Fitzwater,Healthcare Sales Certification Points (EAST 6-...,Healthcare Sales Certification Points (EAST 6-...,300,"EDWARDS BUSINESS MACHINES, INC.",406779,Sales/Marketing Representative,Sales/Marketing Representative,Active,...,5.503190e+11,NaN,AARON FITZWATER,HEALTHCARE SALES CERTIFICATION POINTS (EAST 6-...,1308823,406779,aaron_fitzwater,2024-06-26 05:02:00,both,True

In [26]:
manual_ledger.columns

Index(['FulfillmentDate_manual', 'ParticipantName', 'PromotionName_manual',
       'PromoDisplayName', 'PointsPaid', 'EntityName_manual', 'EntityID',
       'CurrentTitle', 'Participant Title On Paid Date', 'ContactStatus',
       'Hierarchy_manual', 'PromotionID', 'PSPS_manual',
       'ParticipantName_clean', 'PromotionName_clean_manual',
       'PromotionID_clean', 'EntityID_clean', 'PSPS_clean', 'LedgerId',
       'DataKeyType', 'Fulfillmentdate', 'FirstName', 'LastName', 'FullName',
       'UserName', 'ClientParticipantId', 'EntityName_ledger',
       'ClientEntityId', 'Title', 'Hierarchy_ledger', 'ProgramName',
       'PromotionId', 'PromotionName_ledger', 'PromotionDisplayName',
       'AwardType', 'PointsEarned', 'DollarsEarned', 'PromotionType',
       'Comments', 'PersonEID', 'ProgramEID', 'DataSource', 'GameName',
       'GamePlaysEarned', 'PSPS_ledger', 'PromoSalesType', 'FullName_clean',
       'PromotionName_clean_ledger', 'PromotionId_clean',
       'ClientEntityId_clean', 'ClientParticipantId_clean',
       'FulfillmentDate_ledger', '_merge', 'AmountMatch'],
      dtype='str')

In [27]:
len(manual_ledger)

5368

Step 3: Full Reconciliation Chain
Now connect all three:

In [28]:
claims.columns

Index(['InvoiceNumber', 'ClaimEId', 'EntityClaimItemEID', 'ClaimFormName',
       'ClaimSubmittedDate', 'ClaimItemStatus', 'ClaimStatusReason',
       'AwardDate', 'AwardAmount', 'PromotionName', 'ParticipantId',
       'ParticipantName', 'ParticipantTitle', 'ParticipantEmailAddress',
       'ProductName', 'ProductId', 'ProductSerialNumber', 'Quantity',
       'SaleDate', 'CommentText', 'InternalComment', 'LIIndustryId',
       'CompetitorKnockOut', 'EntityName', 'EntityId', 'PSPS',
       'PromoSalesType', 'MasterDealerID', 'MasterDealerName',
       'DealerSoldToID', 'DealerSoldToName', 'ParticipantName_clean',
       'PromotionName_clean', 'ParticipantId_clean', 'EntityId_clean',
       'PSPS_clean'],
      dtype='str')

In [29]:
ledger.columns

Index(['LedgerId', 'DataKeyType', 'Fulfillmentdate', 'FirstName', 'LastName',
       'FullName', 'UserName', 'ClientParticipantId', 'EntityName',
       'ClientEntityId', 'Title', 'Hierarchy', 'ProgramName', 'PromotionId',
       'PromotionName', 'PromotionDisplayName', 'AwardType', 'PointsEarned',
       'DollarsEarned', 'PromotionType', 'Comments', 'PersonEID', 'ProgramEID',
       'DataSource', 'GameName', 'GamePlaysEarned', 'PSPS', 'PromoSalesType',
       'FullName_clean', 'PromotionName_clean', 'PromotionId_clean',
       'ClientEntityId_clean', 'ClientParticipantId_clean', 'PSPS_clean',
       'FulfillmentDate'],
      dtype='str')

In [30]:
manual.columns

Index(['FulfillmentDate', 'ParticipantName', 'PromotionName',
       'PromoDisplayName', 'PointsPaid', 'EntityName', 'EntityID',
       'CurrentTitle', 'Participant Title On Paid Date', 'ContactStatus',
       'Hierarchy', 'PromotionID', 'PSPS', 'ParticipantName_clean',
       'PromotionName_clean', 'PromotionID_clean', 'EntityID_clean',
       'PSPS_clean'],
      dtype='str')

In [31]:
full_chain = claims.merge(
    ledger,
    left_on=[
        "PSPS",
        "EntityId",
        "ParticipantId",
        "PromotionName_clean"
    ],

    right_on=[
        "PSPS",
        "ClientEntityId",
        "ClientParticipantId",
        "PromotionName_clean"
    ],
    how="left",
    suffixes=("_claim", "_ledger")
)

full_chain = full_chain.merge(
    manual,
    left_on=[
        "PSPS",
        "PromotionId",
        "ClientEntityId",
        "PromotionName_clean"
    ],
    right_on=[
        "PSPS",
        "PromotionID",
        "EntityID",
        "PromotionName_clean"
    ],
    how="left",
    suffixes=("", "_manual")
)

In [32]:
len(full_chain)

623466

In [33]:
claims["EntityClaimItemEID"].nunique()

123069

In [34]:
print(len(claims))

print(len(full_chain))

159816
623466

In [35]:
match_counts = (
    full_chain.groupby("EntityClaimItemEID")
    .size()
)

match_counts.describe()

count    123069.000000
mean          5.065987
std           8.855416
min           1.000000
25%           1.000000
50%           2.000000
75%           5.000000
max          95.000000
dtype: float64

In [36]:
full_chain[full_chain['ParticipantName_clean'] == 'AARON BOWMAN']

,InvoiceNumber,ClaimEId,EntityClaimItemEID,ClaimFormName,ClaimSubmittedDate,ClaimItemStatus,ClaimStatusReason,AwardDate,AwardAmount,PromotionName_claim,...,EntityID,CurrentTitle,Participant Title On Paid Date,ContactStatus,Hierarchy_manual,PromotionID,ParticipantName_clean_manual,PromotionID_clean,EntityID_clean,PSPS_clean
582856,AaronBowman091120250516am,1834429,1835860,Claim Form v2,2025-09-12,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
595054,504949486,2063491,2063490,Claim Form v2,2025-12-22,Processed,Completed,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
full_chain.to_csv("full_chain.csv", index=False)

In [39]:
full_chain.columns

Index(['InvoiceNumber', 'ClaimEId', 'EntityClaimItemEID', 'ClaimFormName',
       'ClaimSubmittedDate', 'ClaimItemStatus', 'ClaimStatusReason',
       'AwardDate', 'AwardAmount', 'PromotionName_claim', 'ParticipantId',
       'ParticipantName', 'ParticipantTitle', 'ParticipantEmailAddress',
       'ProductName', 'ProductId', 'ProductSerialNumber', 'Quantity',
       'SaleDate', 'CommentText', 'InternalComment', 'LIIndustryId',
       'CompetitorKnockOut', 'EntityName_claim', 'EntityId', 'PSPS',
       'PromoSalesType_claim', 'MasterDealerID', 'MasterDealerName',
       'DealerSoldToID', 'DealerSoldToName', 'ParticipantName_clean',
       'PromotionName_clean', 'ParticipantId_clean', 'EntityId_clean',
       'PSPS_clean_claim', 'LedgerId', 'DataKeyType', 'Fulfillmentdate',
       'FirstName', 'LastName', 'FullName', 'UserName', 'ClientParticipantId',
       'EntityName_ledger', 'ClientEntityId', 'Title', 'Hierarchy',
       'ProgramName', 'PromotionId', 'PromotionName_ledger',
       'PromotionDisplayName', 'AwardType', 'PointsEarned', 'DollarsEarned',
       'PromotionType', 'Comments', 'PersonEID', 'ProgramEID', 'DataSource',
       'GameName', 'GamePlaysEarned', 'PromoSalesType_ledger',
       'FullName_clean', 'PromotionId_clean', 'ClientEntityId_clean',
       'ClientParticipantId_clean', 'PSPS_clean_ledger', 'FulfillmentDate',
       'FulfillmentDate_manual', 'ParticipantName_manual', 'PromotionName',
       'PromoDisplayName', 'PointsPaid', 'EntityName', 'EntityID',
       'CurrentTitle', 'Participant Title On Paid Date', 'ContactStatus',
       'Hierarchy_manual', 'PromotionID', 'ParticipantName_clean_manual',
       'PromotionID_clean', 'EntityID_clean', 'PSPS_clean'],
      dtype='str')

Analysis

In [ ]:
import pandas as pd
import numpy as np
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter


# ==========================================================
# CONFIGURATION
# ==========================================================

OUTPUT_FILE = "Business_Insights_Report_v3.xlsx"

CLAIM_ITEM_KEY = "EntityClaimItemEID"
CLAIM_KEY = "ClaimEId"
LEDGER_KEY = "LedgerId"

DATE_COLUMNS = [
    "ClaimSubmittedDate",
    "AwardDate",
    "FulfillmentDate"
]

CLAIM_SIDE_COLUMNS = [
    "EntityClaimItemEID",
    "ClaimEId",
    "ParticipantId",
    "ParticipantName",
    "EntityId",
    "PSPS",
    "PromotionName_claim",
    "ClaimItemStatus",
    "ClaimSubmittedDate"
]

LEDGER_SIDE_COLUMNS = [
    "EntityClaimItemEID",
    "LedgerId",
    "AwardDate",
    "AwardAmount"
]


# ==========================================================
# 1. VALIDATE REQUIRED COLUMNS
# ==========================================================

required_columns = list(
    set(
        CLAIM_SIDE_COLUMNS
        + LEDGER_SIDE_COLUMNS
    )
)

missing_columns = [
    col for col in required_columns
    if col not in full_chain.columns
]

if missing_columns:
    raise ValueError(
        "The following required columns are missing from full_chain: "
        + ", ".join(sorted(missing_columns))
    )


# ==========================================================
# 2. CREATE WORKING COPY
# ==========================================================

df = full_chain.copy()

input_row_count = len(df)


# ==========================================================
# 3. DATE CLEANUP
# ==========================================================

for col in DATE_COLUMNS:
    if col in df.columns:
        df[col] = pd.to_datetime(
            df[col],
            errors="coerce"
        )


# ==========================================================
# 4. STANDARDIZE BLANK IDENTIFIERS
# ==========================================================

identifier_columns = [
    "EntityClaimItemEID",
    "ClaimEId",
    "ParticipantId",
    "EntityId",
    "PSPS",
    "LedgerId"
]

for col in identifier_columns:
    if col in df.columns:
        df[col] = df[col].replace(
            r"^\s*$",
            np.nan,
            regex=True
        )


# ==========================================================
# 5. DATA QUALITY COUNTS BEFORE BUILDING REPORT
# ==========================================================

missing_claim_item_id_rows = (
    df[CLAIM_ITEM_KEY].isna().sum()
)

rows_with_claim_item_id = (
    df[CLAIM_ITEM_KEY].notna().sum()
)

rows_with_ledger_id = (
    df[LEDGER_KEY].notna().sum()
)

unique_claim_items_in_source = (
    df[CLAIM_ITEM_KEY]
    .dropna()
    .nunique()
)

unique_claims_in_source = (
    df[CLAIM_KEY]
    .dropna()
    .nunique()
)

unique_ledger_ids_in_source = (
    df[LEDGER_KEY]
    .dropna()
    .nunique()
)


# ==========================================================
# 6. CLAIM-SIDE CONSISTENCY CHECK
#
# Confirm that claim-side attributes are consistent within
# each EntityClaimItemEID before reducing to one row.
# ==========================================================

claim_consistency = (
    df[
        [
            "EntityClaimItemEID",
            "ClaimEId",
            "ParticipantId",
            "ParticipantName",
            "EntityId",
            "PSPS",
            "PromotionName_claim",
            "ClaimItemStatus",
            "ClaimSubmittedDate"
        ]
    ]
    .dropna(subset=["EntityClaimItemEID"])
    .groupby(
        "EntityClaimItemEID",
        dropna=False
    )
    .agg(
        ClaimEIdVersions=(
            "ClaimEId",
            lambda x: x.dropna().nunique()
        ),
        ParticipantIdVersions=(
            "ParticipantId",
            lambda x: x.dropna().nunique()
        ),
        ParticipantNameVersions=(
            "ParticipantName",
            lambda x: x.dropna().nunique()
        ),
        EntityIdVersions=(
            "EntityId",
            lambda x: x.dropna().nunique()
        ),
        PSPSVersions=(
            "PSPS",
            lambda x: x.dropna().nunique()
        ),
        PromotionVersions=(
            "PromotionName_claim",
            lambda x: x.dropna().nunique()
        ),
        StatusVersions=(
            "ClaimItemStatus",
            lambda x: x.dropna().nunique()
        ),
        SubmittedDateVersions=(
            "ClaimSubmittedDate",
            lambda x: x.dropna().nunique()
        )
    )
    .reset_index()
)

version_columns = [
    col for col in claim_consistency.columns
    if col.endswith("Versions")
]

claim_attribute_conflicts = (
    claim_consistency[
        claim_consistency[version_columns]
        .gt(1)
        .any(axis=1)
    ]
    .copy()
)


# ==========================================================
# 7. CREATE CLAIM-ITEM BASE TABLE
#
# One row per EntityClaimItemEID.
#
# Claim-side fields are taken only from claim data.
# sort_values creates deterministic behavior before
# drop_duplicates.
# ==========================================================

claim_item_base = (
    df[CLAIM_SIDE_COLUMNS]
    .dropna(subset=["EntityClaimItemEID"])
    .sort_values(
        by=[
            "EntityClaimItemEID",
            "ClaimSubmittedDate"
        ],
        na_position="last"
    )
    .drop_duplicates(
        subset=["EntityClaimItemEID"],
        keep="first"
    )
    .rename(
        columns={
            "PromotionName_claim": "PromotionName"
        }
    )
    .reset_index(drop=True)
)


# ==========================================================
# 8. CREATE DISTINCT CLAIM-ITEM / LEDGER CANDIDATE BRIDGE
#
# One row per:
# EntityClaimItemEID + LedgerId + AwardDate + AwardAmount
#
# This makes candidate relationships explicit.
# ==========================================================

candidate_bridge = (
    df[LEDGER_SIDE_COLUMNS]
    .dropna(
        subset=[
            "EntityClaimItemEID",
            "LedgerId"
        ]
    )
    .drop_duplicates()
    .reset_index(drop=True)
)


# ==========================================================
# 9. CANDIDATE-LEVEL SUMMARY
#
# Count ledger IDs, award dates, and award amounts separately.
# This prevents an arbitrary AwardDate or AwardAmount from
# being selected for unresolved claim items.
# ==========================================================

candidate_summary = (
    candidate_bridge
    .groupby(
        "EntityClaimItemEID",
        dropna=False
    )
    .agg(
        DistinctLedgerIds=(
            "LedgerId",
            lambda x: x.dropna().nunique()
        ),
        DistinctAwardDates=(
            "AwardDate",
            lambda x: x.dropna().nunique()
        ),
        DistinctAwardAmounts=(
            "AwardAmount",
            lambda x: x.dropna().nunique()
        ),
        CandidateRows=(
            "LedgerId",
            "size"
        )
    )
    .reset_index()
)


# ==========================================================
# 10. IDENTIFY SINGLE-CANDIDATE ITEMS
# ==========================================================

single_candidate_ids = candidate_summary.loc[
    candidate_summary["DistinctLedgerIds"] == 1,
    "EntityClaimItemEID"
]


# ==========================================================
# 11. CREATE CONFIRMED SINGLE-CANDIDATE AWARD TABLE
#
# Award data is retained only where:
# 1. There is exactly one LedgerId
# 2. There is no conflict in AwardDate
# 3. There is no conflict in AwardAmount
# ==========================================================

single_candidate_bridge = (
    candidate_bridge[
        candidate_bridge["EntityClaimItemEID"]
        .isin(single_candidate_ids)
    ]
    .copy()
)

single_candidate_awards = (
    single_candidate_bridge
    .sort_values(
        by=[
            "EntityClaimItemEID",
            "AwardDate",
            "LedgerId"
        ],
        na_position="last"
    )
    .groupby(
        "EntityClaimItemEID",
        dropna=False
    )
    .agg(
        ConfirmedLedgerId=(
            "LedgerId",
            "first"
        ),
        ConfirmedAwardDate=(
            "AwardDate",
            "first"
        ),
        ConfirmedAwardAmount=(
            "AwardAmount",
            "first"
        ),
        SingleCandidateAwardDateVersions=(
            "AwardDate",
            lambda x: x.dropna().nunique()
        ),
        SingleCandidateAwardAmountVersions=(
            "AwardAmount",
            lambda x: x.dropna().nunique()
        )
    )
    .reset_index()
)


# ==========================================================
# 12. REMOVE CONFLICTING AWARD DETAILS
#
# Even when one LedgerId exists, conflicting dates or amounts
# should not be treated as confirmed.
# ==========================================================

single_candidate_awards[
    "SingleCandidateAwardConflict"
] = np.where(
    (
        single_candidate_awards[
            "SingleCandidateAwardDateVersions"
        ] > 1
    )
    |
    (
        single_candidate_awards[
            "SingleCandidateAwardAmountVersions"
        ] > 1
    ),
    "Yes",
    "No"
)

award_conflict_mask = (
    single_candidate_awards[
        "SingleCandidateAwardConflict"
    ] == "Yes"
)

single_candidate_awards.loc[
    award_conflict_mask,
    [
        "ConfirmedAwardDate",
        "ConfirmedAwardAmount"
    ]
] = np.nan


# ==========================================================
# 13. BUILD FINAL CLAIM-ITEM ANALYTICAL TABLE
# ==========================================================

claim_item_summary = (
    claim_item_base
    .merge(
        candidate_summary,
        on="EntityClaimItemEID",
        how="left",
        validate="one_to_one"
    )
    .merge(
        single_candidate_awards,
        on="EntityClaimItemEID",
        how="left",
        validate="one_to_one"
    )
)


# ==========================================================
# 14. FILL NO-CANDIDATE VALUES
# ==========================================================

count_columns = [
    "DistinctLedgerIds",
    "DistinctAwardDates",
    "DistinctAwardAmounts",
    "CandidateRows"
]

for col in count_columns:
    claim_item_summary[col] = (
        claim_item_summary[col]
        .fillna(0)
        .astype(int)
    )

claim_item_summary[
    "SingleCandidateAwardConflict"
] = (
    claim_item_summary[
        "SingleCandidateAwardConflict"
    ]
    .fillna("Not Applicable")
)


# ==========================================================
# 15. CANDIDATE MATCH STATUS
#
# These names describe candidate relationships only.
# They do not imply confirmed payouts.
# ==========================================================

claim_item_summary[
    "CandidateMatchStatus"
] = np.select(
    [
        claim_item_summary[
            "DistinctLedgerIds"
        ] == 0,

        claim_item_summary[
            "DistinctLedgerIds"
        ] == 1,

        claim_item_summary[
            "DistinctLedgerIds"
        ] > 1
    ],
    [
        "No Candidate Match",
        "Single Candidate Match",
        "Multiple Candidate Matches"
    ],
    default="Unknown"
)


# ==========================================================
# 16. AWARD RESOLUTION STATUS
# ==========================================================

claim_item_summary[
    "AwardResolutionStatus"
] = np.select(
    [
        claim_item_summary[
            "DistinctLedgerIds"
        ] == 0,

        claim_item_summary[
            "DistinctLedgerIds"
        ] > 1,

        (
            claim_item_summary[
                "DistinctLedgerIds"
            ] == 1
        )
        &
        (
            claim_item_summary[
                "SingleCandidateAwardConflict"
            ] == "Yes"
        ),

        (
            claim_item_summary[
                "DistinctLedgerIds"
            ] == 1
        )
        &
        (
            claim_item_summary[
                "ConfirmedAwardDate"
            ].isna()
        ),

        (
            claim_item_summary[
                "DistinctLedgerIds"
            ] == 1
        )
        &
        (
            claim_item_summary[
                "ConfirmedAwardDate"
            ].notna()
        )
    ],
    [
        "Unmatched",
        "Unresolved Multiple Candidates",
        "Single Candidate With Conflicting Award Data",
        "Single Candidate Missing Award Date",
        "Resolved Single Candidate"
    ],
    default="Review Required"
)


# ==========================================================
# 17. CONFIRMED CLAIM-TO-AWARD CYCLE TIME
#
# Cycle time is calculated only from the confirmed award date.
# Multiple-candidate records are not assigned arbitrary dates.
# ==========================================================

claim_item_summary[
    "Days_Claim_to_Award"
] = (
    claim_item_summary[
        "ConfirmedAwardDate"
    ]
    -
    claim_item_summary[
        "ClaimSubmittedDate"
    ]
).dt.days


# ==========================================================
# 18. CYCLE-TIME DATA QUALITY STATUS
# ==========================================================

claim_item_summary[
    "CycleTimeStatus"
] = np.select(
    [
        claim_item_summary[
            "AwardResolutionStatus"
        ] != "Resolved Single Candidate",

        claim_item_summary[
            "ClaimSubmittedDate"
        ].isna(),

        claim_item_summary[
            "ConfirmedAwardDate"
        ].isna(),

        claim_item_summary[
            "Days_Claim_to_Award"
        ] < 0,

        claim_item_summary[
            "Days_Claim_to_Award"
        ] == 0,

        claim_item_summary[
            "Days_Claim_to_Award"
        ] > 0
    ],
    [
        "Not Eligible - Award Unresolved",
        "Not Eligible - Missing Claim Date",
        "Not Eligible - Missing Award Date",
        "Invalid Negative Duration",
        "Valid Same-Day Award",
        "Valid Positive Duration"
    ],
    default="Review Required"
)


# ==========================================================
# 19. VALID CYCLE-TIME DATASET
#
# Retain only zero or positive confirmed cycle times.
# Negative durations remain visible in the exception report.
# ==========================================================

valid_cycle_time = (
    claim_item_summary[
        claim_item_summary[
            "CycleTimeStatus"
        ].isin(
            [
                "Valid Same-Day Award",
                "Valid Positive Duration"
            ]
        )
    ]
    .copy()
)


# ==========================================================
# 20. CYCLE-TIME SUMMARY
# ==========================================================

if not valid_cycle_time.empty:

    cycle_time_series = (
        valid_cycle_time[
            "Days_Claim_to_Award"
        ]
        .dropna()
    )

    cycle_summary = pd.DataFrame(
        {
            "Metric": [
                "Eligible Claim Items",
                "Mean Days",
                "Median Days",
                "25th Percentile",
                "75th Percentile",
                "90th Percentile",
                "95th Percentile",
                "Minimum Days",
                "Maximum Days"
            ],
            "Value": [
                cycle_time_series.count(),
                cycle_time_series.mean(),
                cycle_time_series.median(),
                cycle_time_series.quantile(0.25),
                cycle_time_series.quantile(0.75),
                cycle_time_series.quantile(0.90),
                cycle_time_series.quantile(0.95),
                cycle_time_series.min(),
                cycle_time_series.max()
            ]
        }
    )

else:

    cycle_summary = pd.DataFrame(
        {
            "Metric": [
                "Eligible Claim Items"
            ],
            "Value": [
                0
            ]
        }
    )


# ==========================================================
# 21. AWARD-TIME BUCKETS
#
# These are claim-to-award buckets, not fulfillment buckets.
# ==========================================================

claim_item_summary[
    "AwardTimeBucket"
] = pd.cut(
    claim_item_summary[
        "Days_Claim_to_Award"
    ],
    bins=[
        -0.001,
        7,
        30,
        60,
        90,
        np.inf
    ],
    labels=[
        "0-7 Days",
        "8-30 Days",
        "31-60 Days",
        "61-90 Days",
        "90+ Days"
    ],
    include_lowest=True
)

award_time_distribution = (
    claim_item_summary[
        "AwardTimeBucket"
    ]
    .value_counts(
        sort=False,
        dropna=False
    )
    .rename_axis("AwardTimeBucket")
    .reset_index(name="ClaimItems")
)

award_time_distribution[
    "AwardTimeBucket"
] = (
    award_time_distribution[
        "AwardTimeBucket"
    ]
    .astype(str)
    .replace(
        "nan",
        "Not Eligible or Unresolved"
    )
)

award_time_distribution[
    "PercentOfAllClaimItems"
] = (
    award_time_distribution[
        "ClaimItems"
    ]
    /
    len(claim_item_summary)
    * 100
).round(2)


# ==========================================================
# 22. PROMOTION DELAY ANALYSIS
#
# TotalClaimItems shows total population.
# CycleTimeEligibleItems shows the actual denominator used.
# ==========================================================

promo_total = (
    claim_item_summary
    .groupby(
        "PromotionName",
        dropna=False
    )
    .agg(
        TotalClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        )
    )
    .reset_index()
)

promo_cycle = (
    valid_cycle_time
    .groupby(
        "PromotionName",
        dropna=False
    )
    .agg(
        CycleTimeEligibleItems=(
            "EntityClaimItemEID",
            "nunique"
        ),
        AvgDays=(
            "Days_Claim_to_Award",
            "mean"
        ),
        MedianDays=(
            "Days_Claim_to_Award",
            "median"
        ),
        P90Days=(
            "Days_Claim_to_Award",
            lambda x: x.quantile(0.90)
        ),
        MaxDays=(
            "Days_Claim_to_Award",
            "max"
        )
    )
    .reset_index()
)

promo_delay = (
    promo_total
    .merge(
        promo_cycle,
        on="PromotionName",
        how="left",
        validate="one_to_one"
    )
)

promo_delay[
    "CycleTimeEligibleItems"
] = (
    promo_delay[
        "CycleTimeEligibleItems"
    ]
    .fillna(0)
    .astype(int)
)

promo_delay[
    "CycleTimeCoveragePct"
] = (
    promo_delay[
        "CycleTimeEligibleItems"
    ]
    /
    promo_delay[
        "TotalClaimItems"
    ]
    * 100
).round(2)

promo_delay[
    "SampleSizeFlag"
] = np.where(
    promo_delay[
        "CycleTimeEligibleItems"
    ] >= 20,
    "Sufficient for Review",
    "Small Sample - Use Caution"
)

promo_delay = promo_delay.sort_values(
    by=[
        "MedianDays",
        "CycleTimeEligibleItems"
    ],
    ascending=[
        False,
        False
    ],
    na_position="last"
)


# ==========================================================
# 23. ENTITY DELAY ANALYSIS
# ==========================================================

entity_total = (
    claim_item_summary
    .groupby(
        "EntityId",
        dropna=False
    )
    .agg(
        TotalClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        )
    )
    .reset_index()
)

entity_cycle = (
    valid_cycle_time
    .groupby(
        "EntityId",
        dropna=False
    )
    .agg(
        CycleTimeEligibleItems=(
            "EntityClaimItemEID",
            "nunique"
        ),
        AvgDays=(
            "Days_Claim_to_Award",
            "mean"
        ),
        MedianDays=(
            "Days_Claim_to_Award",
            "median"
        ),
        P90Days=(
            "Days_Claim_to_Award",
            lambda x: x.quantile(0.90)
        ),
        MaxDays=(
            "Days_Claim_to_Award",
            "max"
        )
    )
    .reset_index()
)

entity_delay = (
    entity_total
    .merge(
        entity_cycle,
        on="EntityId",
        how="left",
        validate="one_to_one"
    )
)

entity_delay[
    "CycleTimeEligibleItems"
] = (
    entity_delay[
        "CycleTimeEligibleItems"
    ]
    .fillna(0)
    .astype(int)
)

entity_delay[
    "CycleTimeCoveragePct"
] = (
    entity_delay[
        "CycleTimeEligibleItems"
    ]
    /
    entity_delay[
        "TotalClaimItems"
    ]
    * 100
).round(2)

entity_delay[
    "SampleSizeFlag"
] = np.where(
    entity_delay[
        "CycleTimeEligibleItems"
    ] >= 20,
    "Sufficient for Review",
    "Small Sample - Use Caution"
)

entity_delay = entity_delay.sort_values(
    by=[
        "MedianDays",
        "CycleTimeEligibleItems"
    ],
    ascending=[
        False,
        False
    ],
    na_position="last"
)


# ==========================================================
# 24. CANDIDATE MATCH DISTRIBUTION
# ==========================================================

candidate_distribution = (
    claim_item_summary[
        "CandidateMatchStatus"
    ]
    .value_counts(dropna=False)
    .rename_axis(
        "CandidateMatchStatus"
    )
    .reset_index(
        name="ClaimItems"
    )
)

candidate_distribution[
    "Percent"
] = (
    candidate_distribution[
        "ClaimItems"
    ]
    /
    len(claim_item_summary)
    * 100
).round(2)


# ==========================================================
# 25. AWARD RESOLUTION DISTRIBUTION
# ==========================================================

award_resolution_distribution = (
    claim_item_summary[
        "AwardResolutionStatus"
    ]
    .value_counts(dropna=False)
    .rename_axis(
        "AwardResolutionStatus"
    )
    .reset_index(
        name="ClaimItems"
    )
)

award_resolution_distribution[
    "Percent"
] = (
    award_resolution_distribution[
        "ClaimItems"
    ]
    /
    len(claim_item_summary)
    * 100
).round(2)


# ==========================================================
# 26. MULTIPLE CANDIDATE MATCHES
#
# This does not claim that multiple payouts occurred.
# ==========================================================

multiple_candidate_matches = (
    claim_item_summary[
        claim_item_summary[
            "DistinctLedgerIds"
        ] > 1
    ]
    .sort_values(
        by=[
            "DistinctLedgerIds",
            "EntityClaimItemEID"
        ],
        ascending=[
            False,
            True
        ]
    )
    .copy()
)


# ==========================================================
# 27. MULTIPLE-CANDIDATE RATE BY PROMOTION
# ==========================================================

promo_candidate_rates = (
    claim_item_summary
    .groupby(
        "PromotionName",
        dropna=False
    )
    .agg(
        TotalClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        ),
        NoCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "No Candidate Match"
            ).sum()
        ),
        SingleCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "Single Candidate Match"
            ).sum()
        ),
        MultipleCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "Multiple Candidate Matches"
            ).sum()
        )
    )
    .reset_index()
)

promo_candidate_rates[
    "MultipleCandidateRatePct"
] = (
    promo_candidate_rates[
        "MultipleCandidateItems"
    ]
    /
    promo_candidate_rates[
        "TotalClaimItems"
    ]
    * 100
).round(2)

promo_candidate_rates[
    "NoCandidateRatePct"
] = (
    promo_candidate_rates[
        "NoCandidateItems"
    ]
    /
    promo_candidate_rates[
        "TotalClaimItems"
    ]
    * 100
).round(2)

promo_candidate_rates[
    "SampleSizeFlag"
] = np.where(
    promo_candidate_rates[
        "TotalClaimItems"
    ] >= 20,
    "Sufficient for Review",
    "Small Sample - Use Caution"
)

promo_candidate_rates = (
    promo_candidate_rates
    .sort_values(
        by=[
            "MultipleCandidateRatePct",
            "TotalClaimItems"
        ],
        ascending=[
            False,
            False
        ]
    )
)


# ==========================================================
# 28. CONFIRMED AWARD ANALYSIS
#
# Only resolved single-candidate items contain confirmed
# award details.
# ==========================================================

confirmed_award_analysis = (
    claim_item_summary[
        [
            "EntityClaimItemEID",
            "ClaimEId",
            "ParticipantId",
            "EntityId",
            "PSPS",
            "PromotionName",
            "ClaimItemStatus",
            "ClaimSubmittedDate",
            "ConfirmedLedgerId",
            "ConfirmedAwardDate",
            "ConfirmedAwardAmount",
            "Days_Claim_to_Award",
            "CycleTimeStatus",
            "AwardResolutionStatus"
        ]
    ]
    .copy()
)


# ==========================================================
# 29. PARTICIPANT ANALYSIS
# ==========================================================

participant_analysis = (
    claim_item_summary
    .groupby(
        "ParticipantId",
        dropna=False
    )
    .agg(
        ClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        ),
        Claims=(
            "ClaimEId",
            "nunique"
        ),
        NoCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "No Candidate Match"
            ).sum()
        ),
        SingleCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "Single Candidate Match"
            ).sum()
        ),
        MultipleCandidateItems=(
            "CandidateMatchStatus",
            lambda x: (
                x == "Multiple Candidate Matches"
            ).sum()
        ),
        ResolvedAwardItems=(
            "AwardResolutionStatus",
            lambda x: (
                x == "Resolved Single Candidate"
            ).sum()
        )
    )
    .reset_index()
    .sort_values(
        "ClaimItems",
        ascending=False
    )
)


# ==========================================================
# 30. CLAIM ITEMS WITH NO CANDIDATE MATCH
# ==========================================================

no_candidate_items = (
    claim_item_summary[
        claim_item_summary[
            "CandidateMatchStatus"
        ] == "No Candidate Match"
    ]
    .copy()
)

no_candidate_summary = (
    no_candidate_items
    .groupby(
        "PromotionName",
        dropna=False
    )
    .agg(
        ClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        ),
        Claims=(
            "ClaimEId",
            "nunique"
        ),
        Participants=(
            "ParticipantId",
            "nunique"
        )
    )
    .reset_index()
    .sort_values(
        "ClaimItems",
        ascending=False
    )
)


# ==========================================================
# 31. CYCLE-TIME EXCEPTIONS
# ==========================================================

cycle_time_exceptions = (
    claim_item_summary[
        ~claim_item_summary[
            "CycleTimeStatus"
        ].isin(
            [
                "Valid Same-Day Award",
                "Valid Positive Duration"
            ]
        )
    ]
    .copy()
    .sort_values(
        by=[
            "CycleTimeStatus",
            "EntityClaimItemEID"
        ]
    )
)


# ==========================================================
# 32. SINGLE-CANDIDATE AWARD CONFLICTS
# ==========================================================

single_candidate_conflicts = (
    claim_item_summary[
        claim_item_summary[
            "SingleCandidateAwardConflict"
        ] == "Yes"
    ]
    .copy()
)


# ==========================================================
# 33. RECONCILIATION CONTROLS
# ==========================================================

total_analytical_claim_items = len(
    claim_item_summary
)

no_candidate_count = (
    claim_item_summary[
        "CandidateMatchStatus"
    ]
    .eq("No Candidate Match")
    .sum()
)

single_candidate_count = (
    claim_item_summary[
        "CandidateMatchStatus"
    ]
    .eq("Single Candidate Match")
    .sum()
)

multiple_candidate_count = (
    claim_item_summary[
        "CandidateMatchStatus"
    ]
    .eq("Multiple Candidate Matches")
    .sum()
)

candidate_category_total = (
    no_candidate_count
    + single_candidate_count
    + multiple_candidate_count
)

resolved_award_count = (
    claim_item_summary[
        "AwardResolutionStatus"
    ]
    .eq("Resolved Single Candidate")
    .sum()
)

valid_cycle_time_count = len(
    valid_cycle_time
)

negative_cycle_time_count = (
    claim_item_summary[
        "Days_Claim_to_Award"
    ]
    .lt(0)
    .sum()
)

same_day_cycle_time_count = (
    claim_item_summary[
        "Days_Claim_to_Award"
    ]
    .eq(0)
    .sum()
)

reconciliation_controls = pd.DataFrame(
    {
        "Control": [
            "Input full_chain rows",
            "Rows with EntityClaimItemEID",
            "Rows missing EntityClaimItemEID",
            "Rows with LedgerId",
            "Unique claim items in source",
            "Claim items in analytical layer",
            "Claim-item count preserved",
            "Unique claims in source",
            "Distinct ledger IDs in source",
            "No candidate match items",
            "Single candidate match items",
            "Multiple candidate match items",
            "Candidate category total",
            "Candidate categories reconcile",
            "Resolved single-candidate awards",
            "Valid cycle-time items",
            "Same-day award items",
            "Negative cycle-time exceptions",
            "Claim attribute conflict items",
            "Single-candidate award conflict items"
        ],
        "Value": [
            input_row_count,
            rows_with_claim_item_id,
            missing_claim_item_id_rows,
            rows_with_ledger_id,
            unique_claim_items_in_source,
            total_analytical_claim_items,
            (
                unique_claim_items_in_source
                == total_analytical_claim_items
            ),
            unique_claims_in_source,
            unique_ledger_ids_in_source,
            no_candidate_count,
            single_candidate_count,
            multiple_candidate_count,
            candidate_category_total,
            (
                candidate_category_total
                == total_analytical_claim_items
            ),
            resolved_award_count,
            valid_cycle_time_count,
            same_day_cycle_time_count,
            negative_cycle_time_count,
            len(claim_attribute_conflicts),
            len(single_candidate_conflicts)
        ]
    }
)


# ==========================================================
# 34. EXECUTIVE KPIs
# ==========================================================

unique_participants = (
    claim_item_summary[
        "ParticipantId"
    ]
    .dropna()
    .nunique()
)

candidate_match_rate = (
    (
        single_candidate_count
        + multiple_candidate_count
    )
    /
    total_analytical_claim_items
    * 100
    if total_analytical_claim_items > 0
    else 0
)

no_candidate_rate = (
    no_candidate_count
    /
    total_analytical_claim_items
    * 100
    if total_analytical_claim_items > 0
    else 0
)

single_candidate_rate = (
    single_candidate_count
    /
    total_analytical_claim_items
    * 100
    if total_analytical_claim_items > 0
    else 0
)

multiple_candidate_rate = (
    multiple_candidate_count
    /
    total_analytical_claim_items
    * 100
    if total_analytical_claim_items > 0
    else 0
)

cycle_time_coverage_rate = (
    valid_cycle_time_count
    /
    total_analytical_claim_items
    * 100
    if total_analytical_claim_items > 0
    else 0
)

kpis = pd.DataFrame(
    {
        "Metric": [
            "Unique Claims",
            "Unique Claim Items",
            "Unique Participants",
            "Distinct Ledger IDs",
            "No Candidate Match Items",
            "Single Candidate Match Items",
            "Multiple Candidate Match Items",
            "Candidate Match Rate Pct",
            "No Candidate Rate Pct",
            "Single Candidate Rate Pct",
            "Multiple Candidate Rate Pct",
            "Resolved Single-Candidate Awards",
            "Valid Cycle-Time Items",
            "Cycle-Time Coverage Pct",
            "Negative Cycle-Time Exceptions",
            "Claim Attribute Conflict Items",
            "Single-Candidate Award Conflict Items"
        ],
        "Value": [
            claim_item_summary[
                "ClaimEId"
            ].nunique(),
            claim_item_summary[
                "EntityClaimItemEID"
            ].nunique(),
            unique_participants,
            unique_ledger_ids_in_source,
            no_candidate_count,
            single_candidate_count,
            multiple_candidate_count,
            round(candidate_match_rate, 2),
            round(no_candidate_rate, 2),
            round(single_candidate_rate, 2),
            round(multiple_candidate_rate, 2),
            resolved_award_count,
            valid_cycle_time_count,
            round(cycle_time_coverage_rate, 2),
            negative_cycle_time_count,
            len(claim_attribute_conflicts),
            len(single_candidate_conflicts)
        ]
    }
)


# ==========================================================
# 35. METHODOLOGY NOTES
# ==========================================================

methodology_notes = pd.DataFrame(
    {
        "Topic": [
            "Analytical Grain",
            "Candidate Definition",
            "No Candidate Match",
            "Single Candidate Match",
            "Multiple Candidate Matches",
            "Confirmed Award",
            "Cycle Time",
            "Negative Cycle Time",
            "Promotion and Entity Delays",
            "Sample Size",
            "Important Limitation"
        ],
        "Definition": [
            "One analytical row represents one EntityClaimItemEID.",
            "A candidate is a distinct LedgerId connected to an EntityClaimItemEID in full_chain.",
            "The claim item has zero distinct LedgerId values in full_chain.",
            "The claim item has exactly one distinct LedgerId in full_chain.",
            "The claim item has more than one distinct LedgerId in full_chain. This does not by itself prove multiple payouts.",
            "Award details are treated as confirmed only for a single-candidate item without conflicting award dates or award amounts.",
            "Days from ClaimSubmittedDate to ConfirmedAwardDate. Only resolved single-candidate records with non-negative durations are included in valid cycle-time summaries.",
            "A negative duration is retained as a data-quality exception and excluded from valid cycle-time summaries.",
            "Delay statistics use only valid cycle-time records. TotalClaimItems and CycleTimeEligibleItems are reported separately.",
            "Groups with fewer than 20 eligible cycle-time records are marked Small Sample - Use Caution.",
            "The accuracy of candidate relationships depends on the upstream joins used to create full_chain. This report validates and summarizes full_chain but does not independently prove that every upstream match is correct."
        ]
    }
)


# ==========================================================
# 36. EXPORT REPORT
# ==========================================================

with pd.ExcelWriter(
    OUTPUT_FILE,
    engine="openpyxl",
    datetime_format="mm/dd/yyyy",
    date_format="mm/dd/yyyy"
) as writer:

    kpis.to_excel(
        writer,
        sheet_name="Executive_KPIs",
        index=False
    )

    reconciliation_controls.to_excel(
        writer,
        sheet_name="Reconciliation_Controls",
        index=False
    )

    methodology_notes.to_excel(
        writer,
        sheet_name="Methodology_Notes",
        index=False
    )

    candidate_distribution.to_excel(
        writer,
        sheet_name="Candidate_Distribution",
        index=False
    )

    award_resolution_distribution.to_excel(
        writer,
        sheet_name="Award_Resolution",
        index=False
    )

    cycle_summary.to_excel(
        writer,
        sheet_name="Cycle_Time_Summary",
        index=False
    )

    promo_delay.to_excel(
        writer,
        sheet_name="Promotion_Delays",
        index=False
    )

    entity_delay.to_excel(
        writer,
        sheet_name="Entity_Delays",
        index=False
    )

    promo_candidate_rates.to_excel(
        writer,
        sheet_name="Promo_Candidate_Rates",
        index=False
    )

    multiple_candidate_matches.to_excel(
        writer,
        sheet_name="Multiple_Candidates",
        index=False
    )

    confirmed_award_analysis.to_excel(
        writer,
        sheet_name="Confirmed_Awards",
        index=False
    )

    award_time_distribution.to_excel(
        writer,
        sheet_name="Award_Time_Buckets",
        index=False
    )

    participant_analysis.to_excel(
        writer,
        sheet_name="Top_Participants",
        index=False
    )

    no_candidate_summary.to_excel(
        writer,
        sheet_name="No_Candidate_Summary",
        index=False
    )

    no_candidate_items.to_excel(
        writer,
        sheet_name="No_Candidate_Detail",
        index=False
    )

    cycle_time_exceptions.to_excel(
        writer,
        sheet_name="Cycle_Time_Exceptions",
        index=False
    )

    claim_attribute_conflicts.to_excel(
        writer,
        sheet_name="Claim_Attr_Conflicts",
        index=False
    )

    single_candidate_conflicts.to_excel(
        writer,
        sheet_name="Award_Data_Conflicts",
        index=False
    )

    candidate_bridge.to_excel(
        writer,
        sheet_name="Candidate_Bridge",
        index=False
    )

    claim_item_summary.to_excel(
        writer,
        sheet_name="Claim_Item_Detail",
        index=False
    )

    # ======================================================
    # 37. BASIC EXCEL FORMATTING
    # ======================================================

    workbook = writer.book

    header_fill = PatternFill(
        fill_type="solid",
        fgColor="1F4E78"
    )

    header_font = Font(
        color="FFFFFF",
        bold=True
    )

    exception_fill = PatternFill(
        fill_type="solid",
        fgColor="FFF2CC"
    )

    for worksheet in workbook.worksheets:

        worksheet.freeze_panes = "A2"
        worksheet.auto_filter.ref = worksheet.dimensions

        for cell in worksheet[1]:
            cell.fill = header_fill
            cell.font = header_font
            cell.alignment = Alignment(
                horizontal="left",
                vertical="center"
            )

        for row in worksheet.iter_rows():
            for cell in row:
                cell.alignment = Alignment(
                    horizontal="left",
                    vertical="top"
                )

        for column_cells in worksheet.columns:

            column_letter = get_column_letter(
                column_cells[0].column
            )

            max_length = 0

            for cell in column_cells:

                if cell.value is not None:
                    cell_length = len(
                        str(cell.value)
                    )

                    max_length = max(
                        max_length,
                        cell_length
                    )

            worksheet.column_dimensions[
                column_letter
            ].width = min(
                max(max_length + 2, 12),
                45
            )

        # Apply date display to date columns
        for cell in worksheet[1]:
            if cell.value in [
                "ClaimSubmittedDate",
                "AwardDate",
                "FulfillmentDate",
                "ConfirmedAwardDate"
            ]:

                date_column = cell.column

                for row_number in range(
                    2,
                    worksheet.max_row + 1
                ):
                    worksheet.cell(
                        row=row_number,
                        column=date_column
                    ).number_format = "mm/dd/yyyy"

        # Highlight exception sheets
        if worksheet.title in [
            "Cycle_Time_Exceptions",
            "Claim_Attr_Conflicts",
            "Award_Data_Conflicts"
        ]:
            for row in worksheet.iter_rows(min_row=2):
                for cell in row:
                    cell.fill = exception_fill
                    cell.font = Font(
                        color="000000",
                        bold=True
                    )


# ==========================================================
# 38. FINAL VALIDATION
# ==========================================================

assert (
    len(claim_item_summary)
    ==
    claim_item_summary[
        "EntityClaimItemEID"
    ].nunique()
), (
    "Validation failed: claim_item_summary "
    "does not contain one row per EntityClaimItemEID."
)

assert (
    candidate_category_total
    ==
    len(claim_item_summary)
), (
    "Validation failed: candidate categories "
    "do not reconcile to total claim items."
)

assert (
    claim_item_summary[
        "EntityClaimItemEID"
    ].notna().all()
), (
    "Validation failed: final analytical layer "
    "contains missing EntityClaimItemEID values."
)


# ==========================================================
# 39. PRINT RUN SUMMARY
# ==========================================================

print("=" * 65)
print(f"{OUTPUT_FILE} created successfully")
print("=" * 65)

print(
    "Input full_chain rows:",
    f"{input_row_count:,}"
)

print(
    "Unique claim items:",
    f"{total_analytical_claim_items:,}"
)

print(
    "No candidate matches:",
    f"{no_candidate_count:,}"
)

print(
    "Single candidate matches:",
    f"{single_candidate_count:,}"
)

print(
    "Multiple candidate matches:",
    f"{multiple_candidate_count:,}"
)

print(
    "Resolved single-candidate awards:",
    f"{resolved_award_count:,}"
)

print(
    "Valid cycle-time items:",
    f"{valid_cycle_time_count:,}"
)

print(
    "Negative cycle-time exceptions:",
    f"{negative_cycle_time_count:,}"
)

print(
    "Claim attribute conflict items:",
    f"{len(claim_attribute_conflicts):,}"
)

print(
    "Single-candidate award conflict items:",
    f"{len(single_candidate_conflicts):,}"
)

print(
    "Rows missing EntityClaimItemEID:",
    f"{missing_claim_item_id_rows:,}"
)

print("=" * 65)

SyntaxError: invalid syntax (3581439220.py, line 1811)

In [40]:
import pandas as pd
import numpy as np

# ==========================================================
# 1. DATE CLEANUP
# ==========================================================

date_cols = [
    "ClaimSubmittedDate",
    "AwardDate",
    "FulfillmentDate"
]

for col in date_cols:
    if col in full_chain.columns:
        full_chain[col] = pd.to_datetime(
            full_chain[col],
            errors="coerce"
        )

# ==========================================================
# 2. CLAIM ITEM ANALYTICAL LAYER
#    ONE ROW = ONE EntityClaimItemEID
# ==========================================================

claim_item_summary = (
    full_chain
    .groupby("EntityClaimItemEID")
    .agg(
        ClaimEId=("ClaimEId","first"),

        ParticipantId=("ParticipantId","first"),

        ParticipantName=(
            "ParticipantName",
            "first"
        ),

        EntityId=("EntityId","first"),

        PSPS=("PSPS","first"),

        PromotionName=(
            "PromotionName_claim",
            "first"
        ),

        ClaimItemStatus=(
            "ClaimItemStatus",
            "first"
        ),

        ClaimSubmittedDate=(
            "ClaimSubmittedDate",
            "first"
        ),

        AwardDate=(
            "AwardDate",
            "first"
        ),

        AwardAmount=(
            "AwardAmount",
            "first"
        ),

        DistinctLedgerIds=(
            "LedgerId",
            lambda x: x.dropna().nunique()
        )
    )
    .reset_index()
)

# ==========================================================
# 3. PAYOUT STATUS
# ==========================================================

claim_item_summary["PayoutStatus"] = np.select(
    [
        claim_item_summary["DistinctLedgerIds"] == 0,
        claim_item_summary["DistinctLedgerIds"] == 1,
        claim_item_summary["DistinctLedgerIds"] > 1
    ],
    [
        "No Candidate",
        "Single Candidate",
        "Multiple Candidates"
    ],
    default="Unknown"
)

# ==========================================================
# 4. CYCLE TIME METRICS
# ==========================================================

claim_item_summary["Days_Claim_to_Award"] = (
    claim_item_summary["AwardDate"]
    -
    claim_item_summary["ClaimSubmittedDate"]
).dt.days

cycle_summary = (
    claim_item_summary[
        ["Days_Claim_to_Award"]
    ]
    .describe()
)

# ==========================================================
# 5. PROMOTION DELAYS
# ==========================================================

promo_delay = (
    claim_item_summary
    .groupby("PromotionName")
    .agg(
        ClaimItems=("EntityClaimItemEID","nunique"),
        AvgDays=("Days_Claim_to_Award","mean"),
        MedianDays=("Days_Claim_to_Award","median"),
        MaxDays=("Days_Claim_to_Award","max")
    )
    .sort_values(
        "AvgDays",
        ascending=False
    )
)

# ==========================================================
# 6. ENTITY DELAYS
# ==========================================================

entity_delay = (
    claim_item_summary
    .groupby("EntityId")
    .agg(
        ClaimItems=("EntityClaimItemEID","nunique"),
        AvgDays=("Days_Claim_to_Award","mean"),
        MedianDays=("Days_Claim_to_Award","median"),
        MaxDays=("Days_Claim_to_Award","max")
    )
    .sort_values(
        "AvgDays",
        ascending=False
    )
)

# ==========================================================
# 7. PAYOUT DISTRIBUTION
# ==========================================================

payout_distribution = (
    claim_item_summary["PayoutStatus"]
    .value_counts()
    .reset_index()
)

payout_distribution.columns = [
    "PayoutStatus",
    "ClaimItems"
]

payout_distribution["Percent"] = (
    payout_distribution["ClaimItems"]
    /
    len(claim_item_summary)
    * 100
).round(2)

# ==========================================================
# 8. MULTIPLE PAYOUTS
# ==========================================================

multiple_payouts = (
    claim_item_summary[
        claim_item_summary["DistinctLedgerIds"] > 1
    ]
    .sort_values(
        "DistinctLedgerIds",
        ascending=False
    )
)

# ==========================================================
# 9. PROMO SPLIT PAYOUTS
# ==========================================================

promo_split = (
    claim_item_summary
    .groupby("PromotionName")
    .agg(
        ClaimItems=("EntityClaimItemEID","nunique"),

        MultipleCandidateItems=(
            "PayoutStatus",
            lambda x: (x == "Multiple Candidates").sum()
        )
    )
    .reset_index()
)

promo_split["SplitRatePct"] = (
    promo_split["MultipleCandidateItems"]
    /
    promo_split["ClaimItems"]
    * 100
).round(2)

promo_split = promo_split.sort_values(
    "SplitRatePct",
    ascending=False
)

# ==========================================================
# 10. AWARD VS POINTS
# ==========================================================
#
# Since candidate payouts are unresolved,
# focus on payout count behavior instead
#
# ==========================================================

award_vs_points = (
    claim_item_summary[
        [
            "EntityClaimItemEID",
            "ClaimEId",
            "AwardAmount",
            "DistinctLedgerIds",
            "PayoutStatus"
        ]
    ]
    .sort_values(
        "DistinctLedgerIds",
        ascending=False
    )
)

# ==========================================================
# 11. FULFILLMENT BUCKETS
# ==========================================================

claim_item_summary["FulfillmentBucket"] = pd.cut(
    claim_item_summary["Days_Claim_to_Award"],
    bins=[-999,7,30,60,90,9999],
    labels=[
        "0-7 Days",
        "8-30 Days",
        "31-60 Days",
        "61-90 Days",
        "90+ Days"
    ]
)

fulfillment_distribution = (
    claim_item_summary["FulfillmentBucket"]
    .value_counts()
    .reset_index()
)

fulfillment_distribution.columns = [
    "Bucket",
    "Count"
]

# ==========================================================
# 12. TOP PARTICIPANTS
# ==========================================================

participant_analysis = (
    claim_item_summary
    .groupby("ParticipantId")
    .agg(
        ClaimItems=("EntityClaimItemEID","nunique")
    )
    .sort_values(
        "ClaimItems",
        ascending=False
    )
)

# ==========================================================
# 13. CLAIMS NO PAYOUT
# ==========================================================

no_payout = (
    claim_item_summary[
        claim_item_summary["PayoutStatus"]
        ==
        "No Candidate"
    ]
)

no_payout_summary = (
    no_payout
    .groupby("PromotionName")
    .agg(
        ClaimItems=(
            "EntityClaimItemEID",
            "nunique"
        ),

        Claims=(
            "ClaimEId",
            "nunique"
        ),

        Participants=(
            "ParticipantId",
            "nunique"
        )
    )
    .reset_index()
    .sort_values(
        "ClaimItems",
        ascending=False
    )
)

# ==========================================================
# 14. EXECUTIVE KPIs
# ==========================================================

kpis = pd.DataFrame(
    {
        "Metric": [
            "Unique Claims",
            "Unique Claim Items",
            "Unique Participants",
            "Distinct Ledger IDs",
            "No Candidate Claim Items",
            "Single Candidate Claim Items",
            "Multiple Candidate Claim Items"
        ],
        "Value": [
            claim_item_summary[
                "ClaimEId"
            ].nunique(),

            claim_item_summary[
                "EntityClaimItemEID"
            ].nunique(),

            claim_item_summary[
                "ParticipantId"
            ].nunique(),

            full_chain[
                "LedgerId"
            ].nunique(),

            (
                claim_item_summary[
                    "PayoutStatus"
                ] == "No Candidate"
            ).sum(),

            (
                claim_item_summary[
                    "PayoutStatus"
                ] == "Single Candidate"
            ).sum(),

            (
                claim_item_summary[
                    "PayoutStatus"
                ] == "Multiple Candidates"
            ).sum()
        ]
    }
)

# ==========================================================
# 15. SAVE REPORT
# ==========================================================

with pd.ExcelWriter(
    "Business_Insights_Report_v2.xlsx",
    engine="openpyxl"
) as writer:

    kpis.to_excel(
        writer,
        sheet_name="Executive_KPIs",
        index=False
    )

    cycle_summary.to_excel(
        writer,
        sheet_name="Cycle_Time_Summary"
    )

    promo_delay.to_excel(
        writer,
        sheet_name="Promotion_Delays"
    )

    entity_delay.to_excel(
        writer,
        sheet_name="Entity_Delays"
    )

    payout_distribution.to_excel(
        writer,
        sheet_name="Payout_Distribution",
        index=False
    )

    multiple_payouts.to_excel(
        writer,
        sheet_name="Multiple_Payouts",
        index=False
    )

    promo_split.to_excel(
        writer,
        sheet_name="Promo_Split_Payouts",
        index=False
    )

    award_vs_points.to_excel(
        writer,
        sheet_name="Award_vs_Points",
        index=False
    )

    fulfillment_distribution.to_excel(
        writer,
        sheet_name="Fulfillment_Buckets",
        index=False
    )

    participant_analysis.to_excel(
        writer,
        sheet_name="Top_Participants"
    )

    no_payout_summary.to_excel(
        writer,
        sheet_name="Claims_No_Payout",
        index=False
    )

print("Business_Insights_Report_v2.xlsx created")

Business_Insights_Report_v2.xlsx created